adventureworks:
  target: postgres
  outputs:
    postgres:
     type: postgres
     path: target/adventureworks.postgres
     threads: 12
    postgres:  
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: adventureworks
      schema: dbo
      threads: 12
